### ISSUE TITLE
Missing URL and constructor in generated type script file

### ISSUE THREAD

**Issue by kitdjine** [blue-veery-gmbh/spring-rest-2-ts#12]
Hi
Thank you for the great job . we are using it and we are very happy with the job you have done.
In one of your generated type script file , there is a variable "baseURL: URL;" . 
How can we do to add it in the generated files?
We have tried to make it work but we fail to have the the base url declared.
Thank you for your help.

**Comment by gunner121** [comment]
Hello
Thank you, it is great to hear that you like it!
Very sorry for the late answer, I've already updated notification settings in GitHub to be up to date with all issues.
I assume you are trying to use Fetch based generator. In this case, we deliver an implementation of services classes and all you have to do is create objects and use them whenever you want.
e.g. private manufacturerCtrl= new ManufacturerCtrl(new URL("your_api_url"));
Konrad

**Comment by tomasz-wozniak75** [comment]
done

**Comment by tomasz-wozniak75** [comment]
done
