### ISSUE TITLE
Add async instruction on method using Promise

### ISSUE THREAD

**Issue by slobberbone** [blue-veery-gmbh/spring-rest-2-ts#13]
First anything else : very good job ! Thank you !
I'm using FetchBasedImplementationGenerator to generate method like : 
   ```
public addMyObject(arg0: MyObject): Promise<MyObject>  {
   const url =  new URL('/api/myObject/add', this.baseURL);
   return fetch(url.toString(), {method: 'GET'}).then(res =>  res.json());
  }
```
I would like to add "async" instruction like : 
   ```
public **async** addMyObject(arg0: MyObject): Promise<MyObject>  {
   const url =  new URL('/api/myObject/add', this.baseURL);
   return fetch(url.toString(), {method: 'GET'}).then(res =>  res.json());
}
```
+ await instructions ...
It seems I could extends TSMethod and override the write method to add isAsync parameter, but I'll prefer to check if it has a sense and if it would be interested to add it ?

**Comment by tomasz-wozniak75** [comment]
Hi, 
thanks :)
We will add async as an option to FetchBasedImplementationGenerator
Tomasz

**Comment by tomasz-wozniak75** [comment]
Now TSMethod has option to set async modifier which is set by FetchBasedImplementationGenerator if it is configured to do it. Change has been released

**Comment by tomasz-wozniak75** [comment]
done
