### ISSUE TITLE
Classes not imported on HashMap

### ISSUE THREAD

**Issue by slobberbone** [blue-veery-gmbh/spring-rest-2-ts#14]
I have a field in a dto wich is a Map<String, ObjectDto>, the typeScript generator translate to 
``` {[key: string]: ObjectModel};```
but ObjectModel is not imported.

**Comment by tomasz-wozniak75** [comment]
Sorry for the late response,  we will fixed it in the new version 1.2.6 on which we are working now

**Comment by tomasz-wozniak75** [comment]
I reproduced Your issue & fixed, version 1.2.6 should be merged to master at the end of next week

**Comment by tomasz-wozniak75** [comment]
fix has been released
