### ISSUE TITLE
How to add custom imports on generators

### ISSUE THREAD

**Issue by BloodWorkXGaming** [blue-veery-gmbh/spring-rest-2-ts#23]
Hello everyone,

This is a very usefull Project!
However our frontend is based on axios and therefore I modifed the fetch based client to be axios based.
My current problem is adding the custom imports that are needed at the top like 
```
import axios from 'axios';
import { AxiosResponse } from 'axios';
```

is there any way to add those?

Here is a gist of my attempt:
https://gist.github.com/BloodWorkXGaming/30ae1c0517d191b12b2f5089d0130145

Thank you! :)

**Comment by tomasz-wozniak75** [comment]
Hey
Thanks for the feedback, we really appreciate that :)
Coming to your problem I see that you've created already external module for axios and interfaces which you want to use from that module (lines 27-30). All you need to do, is to add to your services type usage of axios types, using method `<your service class>.addComplexTypeUsage(complexType)
Please check in angular generator [Angular4ImplementationGenerator](https://github.com/blue-veery-gmbh/spring-rest-2-ts/blob/master/spring-rest2ts-spring/src/main/java/com/blueveery/springrest2ts/implgens/Angular4ImplementationGenerator.java) on line 283 it will clarify what you need to do. After that change, imports will be generated.
In case of any problem just ask I wish you good luck with the implementation and if you would like to contribute your axios generator it will be welcome ;)
Tomasz

**Comment by BloodWorkXGaming** [comment]
Awesome, thank you! That was easier than expected!

Had to do a smal workaround with `new TSClass("default as axios", axiosModule, this);` to get the main axios object, as imports seem to always be inside braces.

I will have to test the axios impl a few more days but then I'll gladly contribute it :)

**Comment by tomasz-wozniak75** [comment]
great :) 
yes we don't support default exports but it is easy to add, we need to add a flag on scoped type that is exported by default and based on that info in TSImport generate import in different way. I will do it in the next release
