### ISSUE TITLE
Patch method doesn't include a payload

### ISSUE THREAD

**Issue by TiagoJacobs** [blue-veery-gmbh/spring-rest-2-ts#32]
Hello, the patch generated method is currently not including a payload.

I think this method could be renamed: https://github.com/blue-veery-gmbh/spring-rest-2-ts/blob/master/spring-rest2ts-spring/src/main/java/com/blueveery/springrest2ts/implgens/Angular4ImplementationGenerator.java#L234 

Are you ok with this solution? If so, I can send a PR.

Thanks

**Comment by tomasz-wozniak75** [comment]
Hey Tiago
We didn't use PATCH method at that time so we assumed that no one will needed it :) 
The method name should be something like `requestCouldHaveBody` or `bodyIsAllowed` also better name is welcome and You can add test for PATCH in this method. Please make `version-1.5.0` branch as target of your PR I will make a small release in a day or two after your PR.
Thanks for pointing out this problem
 Tomasz

**Comment by tomasz-wozniak75** [comment]
Hey Tiago
Please try version 1.5.0 it should fix your problem
